### ISSUE TITLE
ID-LSTM

### ISSUE THREAD

**Issue by WOW5678** [keavil/AAAI18-code#9]
作者您好，
看了您的代码，我怎么感觉ID-LSTM代码中actor网络的更新忘记乘以reward这一项了？也许是我的理解有问题，希望您能够解惑。

**Comment by keavil** [comment]
https://github.com/keavil/AAAI18-code/blob/3911ed39c26d5c1e089514ab588bc9657428e21a/ID_LSTM/main.py#L99
